title: "Simeon A. Smith"
description: "welcomes you to his home page. This website contains essays, articles, and other written work."
url: ""
baseurl: ""

markdown: kramdown
permalink: /:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
